### ISSUE TITLE
AttributeError: module 'point_cloud_utils' has no attribute 'sample'

### ISSUE THREAD

**Issue by lelouedec** [fwilliams/point-cloud-utils#1]
`AttributeError: module 'point_cloud_utils' has no attribute 'sample'`
I am trying to use the given example for mesh sampling. And it raises the error above.

**Comment by fwilliams** [comment]
Hey, thanks for posting!

There are a few examples on the main page. Could you post a small example of the code that causes the error?

**Comment by fwilliams** [comment]
@lelouedec  Looks like the Poisson Disk Sampling example was out of date. I updated the README, and it should be correct now. Let me know if you run into any problems or if that wasn't your issue.

**Comment by lelouedec** [comment]
Oh sorry I forgot to specify the error comes from the following example : 
```
import point_cloud_utils as pcu

# v is a nv by 3 NumPy array of vertices
# f is an nf by 3 NumPy array of face indexes into v 
v, f, _, _ = pcu.read_ply("my_model.ply")
bbox = np.max(v, axis=0) - np.min(v, axis=0)
bbox_diag = np.linalg.norm(bbox)

# Generate very dense  random samples on the mesh (v, f)
# v_dense is an array with shape (100*v.shape[0], 3) where each row is a point on the mesh (v, f)
v_dense = pcu.sample_mesh_uniform(v, f, num_samples=v.shape[0]*100)

# Downsample v_dense to be from a blue noise distribution 
# v_poisson is a downsampled version of v where points are separated by approximately 
# `radius` distance, use_geodesic_distance indicates that the distance should be measured on the mesh.
v_poisson = sm.sample_mesh_poisson_disk(v, f, radius=0.01*bbox_diag, use_geodesic_distance=True)
```
And is on this line : 
`v_dense = pcu.sample_mesh_uniform(v, f, num_samples=v.shape[0]*100)`

**Comment by fwilliams** [comment]
@lelouedec Looks like the Poisson Disk Sampling example was out of date. I updated the README, and it should be correct now. Let me know if you run into any problems or if that wasn't your issue.

**Comment by lelouedec** [comment]
> @lelouedec Looks like the Poisson Disk Sampling example was out of date. I updated the README, and it should be correct now. Let me know if you run into any problems.

Alright the function seems to exist with the updated README, however the OBJ read might have a problem. 
On the line : 
`v_dense, n_dense = pcu.sample_mesh_random(v, f, n, num_samples=v.shape[0]*100)`
I get the error : 

> ValueError: Only 3D inputs are supported: v and f must have shape (n, 3) and (m, 3) (n, m > 0). Got v.shape =(8, 3), f.shape = (6, 4).

I tried with multiple different meshes in the OBJ format

**Comment by fwilliams** [comment]
If you're loading `f` from an OBJ, (i.e. `v, f = pcu.readOBJ(...)`) then this likely means you have quads in your mesh. All the functions in pcu assume triangle faces, so you'll need to split your quads into triangles. 

Specifically, `v` should have shape `(n, 3)` and `f` should have shape `(m, 3)`. Your `f` has shape `(6, 4)`.

**Comment by fwilliams** [comment]
I'm closing this since it doesn't seem your issue is related to PCU. Good luck and please open more issues if you find problems :)
