### ISSUE TITLE
read_obj: file not found

### ISSUE THREAD

**Issue by Leerw** [fwilliams/point-cloud-utils#12]
Thanks for your great work!

```
Warning: readOBJ() ignored non-comment line 155880:
  o mesh1.002_mesh1-geometry
Failed to cast FTC to matrix: min (0) != max (3)
Traceback (most recent call last):
  File "prepare_complete.py", line 49, in <module>
    pcd = sampling_from_mesh(mesh_path, pcd_path, num_points, sample_method)
  File "../sampling/sample.py", line 62, in sampling_from_mesh
    v, f, n = pcu.read_obj(mesh)
ValueError: File '/model.obj' not found.
```
but the model.obj does exists! what happened?

**Comment by fwilliams** [comment]
The file `/model.obj` probably doesn't exist. Did you mean `./model.obj`?

**Comment by fwilliams** [comment]
Did this fix the issue?

**Comment by Leerw** [comment]
sorry, I have not fix this issue, the path is correct, but I delete some prefix personal directories to make it looks clean. I have tried to use the `readOBJ` in `libigl`, it worked for me. But why `readOBJ` in `pcu` does not work?

**Comment by fwilliams** [comment]
`read_obj` in PCU just calls libIGL under the hood and the Python binding should be identical. Can you paste the code you ran and the exact error? Also what OS and version of Python are you using?

**Comment by fwilliams** [comment]
I've completely rewritten the Mesh IO functions in point-cloud-utils. They are not much more powerful and flexible and shouldn't suffer from the reported bug. 

See [here for documentation on loading meshes](https://github.com/fwilliams/point-cloud-utils#loading-meshes-and-point-clouds) and [see here for documentation on saving meshes](https://github.com/fwilliams/point-cloud-utils#saving-meshes-and-point-clouds).
