### ISSUE TITLE
Conda for osx-64? 

### ISSUE THREAD

**Issue by chitraa** [fwilliams/point-cloud-utils#2]
Hey it would be nice to have conda module for osx-64. 
When I tried to run pip, 2 errors were generated while building:
`
external/vcglib/eigenlib/Eigen/src/Householder/HouseholderSequence.h:409:31: error: no template named 'is_identity' in namespace 'Eigen::internal'; did you mean 'std::__identity'?
          applyThisOnTheLeft(res, internal::is_identity<OtherDerived>::value && res.rows()==res.cols());
                                  ^~~~~~~~~~~~~~~~~~~~~
                                  std::__identity
    /Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:403:8: note: 'std::__identity' declared here
    struct __identity { typedef _Tp type; };`
`/external/vcglib/eigenlib/Eigen/src/Geometry/Transform.h:915:6: error: use of undeclared identifier 'EIGEN_CONST_CONDITIONAL'
      if(EIGEN_CONST_CONDITIONAL(int(Mode)==int(Projective)))`

Note that I have already have the the following dependencies which are required to install with pip:
- A C++ compiler supporting C++14 or later
- CMake 3.2 or later.
- git

**Comment by fwilliams** [comment]
Hey thanks for the comment!

I've fixed all the compile issues on OSX in the latest version. 

I'm also getting a package on conda-forge for Linux and OSX which should become available in the next few days.

In the meantime, installation with `pip` on OSX should work.

**Comment by chitraa** [comment]
Thanks, works with pip now.

**Comment by fwilliams** [comment]
By the way, this package is now on conda forge so you can install it on whatever platform with 

```
conda install -c conda-forge point_cloud_utils
```
