### ISSUE TITLE
Return barycentric coordinates in mesh sampling functions

### ISSUE THREAD

**Issue by fwilliams** [fwilliams/point-cloud-utils#21]
Currently the mesh sampling functions return points (and possibly normals) which is limiting if the user has attributes stored at mesh vertices. Let's update them to optionally return barycentric coordinates.

**Comment by edward1997104** [comment]
I would like to ask if there is any updates on this because it seems that it will return barycentric coordinates in the README.md

**Comment by edward1997104** [comment]
I think I have figured it out, the function is now in version 0.17.3 which is only available through pip install, but not conda install. Perhaps I might suggest you can update the conda install version as well. Thanks!

**Comment by fwilliams** [comment]
Are you on Windows by any chance? I think this is available in 0.16.0. Unfortunately the windows build uses too much memory and breaks on conda-forge so the latest available Windows version is outdated.

**Comment by edward1997104** [comment]
Thank you for your reply. I am working on the ubuntu 18.04 and using the conda install, but it seems that it does not include the function (even though it said it successfully install the 0.16.0 version).

**Comment by fwilliams** [comment]
Ah yes, it appears you're right! I didn't include this functionality in 16.0. CVPR is in a week and I'm deadline mode so a bit absent minded. 

The reason these changes aren't pushed to conda-forge is twofold:
 1. They're implemented for all the mesh sampling functions except `sample_mesh_lloyd` which works a bit differently and is going to be extra work. I want to keep the API consistent within versions.
 2. I'm almost a done a massive overhaul of the Mesh IO stuff so there will be one function to read/write just about any 3d mesh file (basically if meshlab can open it, so can we). 

Both these changes are API breaking (No API guarantees until v1.0 sorry!) and I want to ship them all at once so there is just one upgrade that breaks everything instead of multiple.

**Comment by edward1997104** [comment]
Thank you for your reply! Wish you all best for the CVPR submission in a week!
