### ISSUE TITLE
pcu.write_ply() throws "Incompatible function arguments error"

### ISSUE THREAD

**Issue by cravisjan97** [fwilliams/point-cloud-utils#22]
I am trying to load a mesh in .obj format, perform Lloyd Relaxation and then save the point clouds to .ply format. I am writing the following code:

```
v,f,n = pcu.read_obj('./data/ChairNoArms9.obj')
samples = pcu.sample_mesh_lloyd(v, f, 15000)
pcu.write_ply(filename='sample.ply', v=samples, f=f, ascii=True)
```

Note: I have no normals in my mesh file

**Comment by cravisjan97** [comment]
I was able to solve the issue by passing in empty numpy arrays to n and uv

**Comment by cravisjan97** [comment]
But the point clouds do not make any sense to the input mesh (which is a chair). Am I doing something wrong here?

**Comment by fwilliams** [comment]
Hey thanks for reporting the issue. Can you upload the mesh so I can try it out? I tried `sample_mesh_lloyd` locally and it seems to work okay.

**Comment by cravisjan97** [comment]
I am using this mesh https://github.com/diegogb/3D_Synthesis_based_on_Fine-grained_Parts/blob/master/data/input/Chairs/ChairArms1.obj.

**Comment by fwilliams** [comment]
Hey, so I just downloaded your mesh and ran `sample_mesh_lloyd` on it. I a screenshot of the results below and code to reproduce it below. 

The results seem quite reasonable to me. For reference, I'm running point_cloud_utils version 0.15.1 installed from conda-forge on a Linux machine. 

Could you post a screenshot showing what was wrong with your point cloud? Could you also post the version of point_cloud_utils and platform you're running on. 

### Reproducing steps
```
v, f, n = pcu.read_obj("ChairArms1.obj")
pts = pcu.sample_mesh_lloyd(v, f, 15000)
```
I plotted the mesh and points using [mayavi](https://anaconda.org/conda-forge/mayavi):
```
from mayavi import mlab
mlab.figure(bgcolor=(0.1, 0.1, 0.1))
mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f)
mlab.triangular_mesh(v[:, 0], v[:, 1], v[:, 2], f, representation='wireframe', color=(0.1, 0.1, 0.1))
mlab.points3d(pts[:, 0], pts[:, 1], pts[:, 2], scale_factor=0.015)
mlab.show()
```

which yield:

![image](https://user-images.githubusercontent.com/1343232/93914097-05df2d80-fcd4-11ea-9ecf-0356a24d7947.png)

**Comment by cravisjan97** [comment]
Is it possible to save the point clouds as .ply file? I am confused with that part of the code. I am saving it as a .ply file and the point clouds do not make any sense.

**Comment by fwilliams** [comment]
Yes you can save the point clouds as a PLY file as follows:

```python
import point_cloud_utils as pcu
import numpy as np

v, f, n = pcu.read_obj("ChairArms1.obj")
pts = pcu.sample_mesh_lloyd(v, f, 15000)

pcu.write_ply("out.ply", v, np.zeros([0, 3], dtype=np.int32), np.zeros([0, 3]), np.zeros([0, 2]))
```

The zero-arrays are just passing empty faces, normals and uv coordinates.

Currently, the interface for MeshIO is not very user unfriendly. I plan on overhauling this completely in the near future so it's no so confusing.

**Comment by cravisjan97** [comment]
I am confused by this. Shouldn't we be passing 'pts' in write_ply function and not 'v'?

**Comment by fwilliams** [comment]
Ah yeah you're right! Sorry I didn't test the code before submitting the responds. I just edited the response.
