### ISSUE TITLE
Is there a function to return the height from the base of a point cloud?

### ISSUE THREAD

**Issue by cravisjan97** [fwilliams/point-cloud-utils#23]

**Comment by fwilliams** [comment]
Hi @cravisjan97 thanks for posting! 

I'm a little bit confused by what you mean by "the height from the base of the point cloud"? I tried to answer the question based on my interpretation of the question, but maybe you specify a bit more detail about what you'd like to do to help me out?

For tho notion of height to make sense, you would need two things: 
1. A base point `x` which is some point on the "ground"
2. An up direction `up` which tells us which way is up.

Given these two quantities, the length of a point cloud is well defined, and you can compute it with
```python
import numpy as np

# Here pts is your point cloud, a numpy array of shape [N, 3]
#          x is a point on the "ground", a numpy array of shape [3]
#          up is a vector pointing up. a numpy array of shape [3]
def measure_length(pts, x, up):
  up /= np.linalg.norm(up)  # up needs to be a unit vector
  x = np.squeeze(x)[np.newaxis, :]  # reshape x so it has shape [1, 3]
  pt_heights = (pts - x) @ up  # project the vector from the ground point to each point onto the up direction
  pcloud_length = np.max(pt_heights) - np.min(pt_heights)
  return pcloud_length
```

If your point `x` is a point in the pointcloud which touches the "ground", then the length along the up direction measures the "height" of the pointcloud.

**Comment by fwilliams** [comment]
Hey @cravisjan97 did I answer your question? Can I close this issue?

**Comment by fwilliams** [comment]
I'm closing this issue since I think the question is answered. Feel free to re-open it if you have any further questions.
