### ISSUE TITLE
Symetrical Sinkhorn loss 

### ISSUE THREAD

**Issue by TheoDEPRELLE** [fwilliams/point-cloud-utils#28]
Hi @fwilliams,

After trying your sinkhorn loss on 2 point cloud it seems that it's not symetrical wrt the 2 set of points. Is that true ?

Best,

**Comment by fwilliams** [comment]
Hi Theo,

Thanks for posting the issue! 

If your two point sets are labelled `X` and `Y` (both arrays of shape `Nx3`), and weights are `a` and `b` (arrays of shape N), then flipping the order of the input sets is equivalent to transposing the distance matrix `M` (`M_ij = ||X_i - Y_j||`) and passing `a` and `b` in the opposite order. i.e.
```python
# Calling sinkhorn with the arguments X and Y flipped
M = np.linalg.norm(X[:, np.newaxis, :] - Y[np.newaxis, :, :], axis=-1)
pcu.sinkhorn(b, a, M.T, eps=...)
```
The matrix `M` is not symmetric unless `X` and `Y` are equal and Sinkhorn is an iterative algorithm, so passing the transpose `M.T` starts the iterations from a different place. Thus, if the number of iterations is too small, then the two calls may not agree to the number digits you expect. The `eps` parameter controls the stop threshold and, thus the number of digits that we expect the two calls to agree in, while `max_iters` controls the maximum number of iterations. Smaller `eps` means longer convergence times, but more digits. If your two calls disagree a lot, try increasing the maximum number of iterations. If you want them to agree in more digits, try decreasing `eps`. 

Let me know if that helps and if you have any more questions, I'm happy to help :smile:

**Comment by fwilliams** [comment]
@TheoDEPRELLE does this answer your question? If so, I'll close the issue.

**Comment by TheoDEPRELLE** [comment]
Yes !

Thanks a lot ;) 

I'm closing the issue
