### ISSUE TITLE
Documentation for Monte-Carlo sampling

### ISSUE THREAD

**Issue by Seikegn** [fwilliams/point-cloud-utils#30]
Dear developer, 
    From README I saw you listed Monte-Carlo sampling as one of the sampling methods provided, yet I can find no clue on how to use a related function, could you please enlighten me?
    Thanks!

**Comment by fwilliams** [comment]
There is an example in the README on how to generate monte-carlo samples on a mesh here:

https://github.com/fwilliams/point-cloud-utils#generate-random-samples-on-a-mesh

**Comment by Seikegn** [comment]
Thank you! I didn't realize the two are the same thing.
