### ISSUE TITLE
In fast k-nearest-neighbor search, do you use approximate methods? 

### ISSUE THREAD

**Issue by nimajam41** [fwilliams/point-cloud-utils#35]
Hello!
The term "fast" made me confused a little. Does it mean that the nearest neighbors are searched using approximate methods? It will be nice if you can provide some information about this function.

**Comment by dancergraham** [comment]
Hello. the documentation says that the KNN search is 'based on' nanoflann, which says that it does not use approximate methods but is fast because it uses KD trees https://github.com/jlblancoc/nanoflann

**Comment by nimajam41** [comment]
@fwilliams and @dancergraham , thanks for your guidance!
