### ISSUE TITLE
TypeError: pairwise_distances() got an unexpected keyword argument 'squeeze'

### ISSUE THREAD

**Issue by ShairozS** [fwilliams/point-cloud-utils#4]
After installing from Conda and copy-pasting the example for Chamfer distance, the following error is thrown.

TypeError: pairwise_distances() got an unexpected keyword argument 'squeeze'

Running on GPU enabled Windows 10 machine. Below is the full example from the main page:

import point_cloud_utils as pcu
import numpy as np

a = np.random.rand(100, 3)
b = np.random.rand(100, 3)

chamfer_dist = pcu.chamfer(a, b)

**Comment by fwilliams** [comment]
Thanks for the bug report!I just fixed this issue. I'm going to cut a new release soon with some other fixes. I'll let you know when you can grab the latest!
