### ISSUE TITLE
shortest_distance_pairs problem

### ISSUE THREAD

**Issue by yokomaz** [fwilliams/point-cloud-utils#47]
Dear sir,
I was trying to use pcu.shortest_distance_pairs to calcul the distance in Knn distance, but it shows me a problem that pcu has no attribute "shortest_distance_pairs"

Verison of pcu is 0.23.0 and it's used as python library.

Do you know how to solve it?

Thanks before

**Comment by fwilliams** [comment]
Hi, 

Thanks for reporting the issue. The README has gotten a bit out of date and the example refers to an old version of PCU. I've updated it and included a snippet of the new way to do this here:

```python
import point_cloud_utils as pcu
import numpy as np

# Generate two random point sets
pts_a = np.random.rand(1000, 3)
pts_b = np.random.rand(500, 3)

k = 10

# dists_a_to_b is of shape (pts_a.shape[0], k) and contains the (sorted) distances 
# to the k nearest points in pts_b
# corrs_a_to_b is of shape (a.shape[0], k) and contains the index into pts_b of the 
# k closest points for each point in pts_a 
dists_a_to_b, corrs_a_to_b = pcu.k_nearest_neighbors(pts_a, pts_b, k)
```
