### ISSUE TITLE
ValueError: Invalid type (float64)

### ISSUE THREAD

**Issue by ShairozS** [fwilliams/point-cloud-utils#5]
The following error is thrown from the sample_mesh_poisson_disk() method

![image](https://user-images.githubusercontent.com/14152951/62344786-537f5200-b4a4-11e9-82b3-fba592c6672d.png)

This is without any modification to the example code, and occurs even with explicit typecasting of the arrays to either float64 or float32

**Comment by fwilliams** [comment]
Hey, thanks a lot for reporting this issue! That error messsage comes from the library [numpyeigen](https://github.com/fwilliams/numpyeigen) which I'm using to generate python bindings. I've bumped the version now which gives clearer error messages and fixes some bugs.

If you have a simple code example that reproduces the error it would also be helpful. The new version (0.7.4) is building on conda-forge now. Once it's done, could you retry the example and let me know if there's still a problem?

**Comment by fwilliams** [comment]
@ShairozS this issue should be fixed in the latest version of the library which is live on conda-forge. Can you confirm that everything works for you so I can close the issue?

**Comment by fwilliams** [comment]
@ShairozS any news?
