### ISSUE TITLE
pairwise_distance returns the distance instead of the squared distance now?

### ISSUE THREAD

**Issue by yiting12** [fwilliams/point-cloud-utils#57]
![Screenshot 2023-01-27 at 13 20 08](https://user-images.githubusercontent.com/38757224/215085678-45a6b071-adfd-4542-badc-49370b8ba53c.png)
I used to work with pcu.pairwise_distance (v0.18.0, conda-forge) and it returned the **squared** distance as shown in the attached screenshot. Recently I download the package pcu 0.29.1 with pip, and it returns the distance directly. I didn't find any update docs regarding this change, and the demo is still showing the example code of the previous version.

**Comment by fwilliams** [comment]
Hi, thank you for pointing this out! I'll update the readme accordingly.

The conda-forge package is very old and deprecated. Unfortunately, conda-forge does not allow deleting packages.

I realize I should have announced this somewhere.

**Comment by fwilliams** [comment]
okay the README is updated, Feel free to reopen this issue if there are any more problems
