### ISSUE TITLE
The wrong result of Ray/Mesh intersection

### ISSUE THREAD

**Issue by EAST-J** [fwilliams/point-cloud-utils#60]
Hi,
I try to calculate the ray/mesh intersection using the sample code. The mesh I used for the sample is a Sphere.  Here is the part code:
`   mesh = trimesh.primitives.Sphere()`
 `  ray_origins = np.array([[0, 0, -5],])`
`   ray_directions = np.array([[0, 0, 1],])`
  ` intersector = pcu.RayMeshIntersector(np.array(mesh.vertices).astype(np.float32), np.array(mesh.faces))`
`   fid, bc, t = intersector.intersect_rays(ray_origins.astype(np.float32), ray_directions.astype(np.float32))`
The result should be [0, 0, -1] and [0, 0, 1], however I get the result as [ 5.9604645e-08  9.9999994e-01 -0.0000000e+00]. Could you give me some hints about the usage of the sample code?

**Comment by EAST-J** [comment]
I get the result as hit pos as [ 7.931656e-09  4.902033e-09 -1.000000e+00], Does this mean that only the nearest intersection will be counted？

**Comment by fwilliams** [comment]
It currently only returns the first intersection but it shouldn’t be that hard to add a function to return multiple intersections along a ray. 

Unfortunately I won’t have time in the near future to do this but if you’re interested, I can point you to where to make the change and describe what to do. 

As a workaround you could call the ray intersector or multiple times perturbing your intersection point by epsilon along the ray. If you use the ‘RayMeshIntersector’ class this should be efficient!

**Comment by EAST-J** [comment]
Thx for your response.
