### ISSUE TITLE
Documentation not loading

### ISSUE THREAD

**Issue by maurock** [fwilliams/point-cloud-utils#61]
Hi @fwilliams ,

It seems like the documentation (and your website) are not loading properly.

![image](https://user-images.githubusercontent.com/30290271/228916724-26298f7d-ceb2-42fc-bc03-a1471a807329.png)

Thanks!

**Comment by fwilliams** [comment]
Thanks for reporting this. I triggered a rebuild of the website and it works now. Very weird!
