### ISSUE TITLE
Point Cloud To mesh

### ISSUE THREAD

**Issue by AlexSteiner30** [fwilliams/point-cloud-utils#64]
Is it possible to convert a point cloud into a mesh?

**Comment by fwilliams** [comment]
Hi, I currently don't have any functions to do this in PCU. I would like to integrate Screened Poisson Surface Reconstruction at some point though. 

In the meantime, you can get Screened Poisson Surface Reconstruction from here: [https://github.com/mkazhdan/PoissonRecon](https://github.com/mkazhdan/PoissonRecon)

**Comment by fwilliams** [comment]
Okay so now that I can talk about it, @AlexSteiner30 you should try NKSR, which is our latest work on this problem and should work quite a bit better than Poisson Reconstruction!!

https://research.nvidia.com/labs/toronto-ai/NKSR/
