### ISSUE TITLE
make_mesh_watertight grows the mesh

### ISSUE THREAD

**Issue by gattia** [fwilliams/point-cloud-utils#71]
Thanks for this awesome library. 

I've been trying to use make_mesh_watertight and noticed that it makes the mesh bigger - and the growth seems to be somewhat related to the resolution. 

If I use a resolution of 5k then the mesh gets quite a bit bigger (image 1). If I used 50k or 100k (image 2) as the resolution it still gets bigger (by ~ the same amount) but less so than 5k. This doesn't seem like it would matter too much for regular use cases - however, I am working with medical data and am calculating things like thickness off of the meshes so this growth can have an affect. I also usually create surfaces for multiple objects and so now that they are all a bit bigger they intersect whereas they didn't previously. 

Just curious if you have encountered this or if you have any thoughts on how to rectify or work around this as the packaged overall seems to do a great job and I'd love to still be able to use it in my pipelines. 

<img width="1073" alt="Screenshot 2023-08-21 at 3 49 57 PM" src="https://github.com/fwilliams/point-cloud-utils/assets/10676083/d0981c0b-a5ed-4182-ada8-867c2acd2c6e">
<img width="1072" alt="Screenshot 2023-08-21 at 3 50 07 PM" src="https://github.com/fwilliams/point-cloud-utils/assets/10676083/c1a48082-8688-4417-89c3-b4d773babe54">

**Comment by fwilliams** [comment]
I think this is just a property of the underlying algorithm which is described here: https://arxiv.org/abs/1802.01698

One hack that might work here is to project each vertex on the blue mesh to it's closest point on the white mesh. You can use `pcu.closest_points_on_mesh` ([Docs and examples here](https://www.fwilliams.info/point-cloud-utils/sections/closest_point_on_mesh/)) to do this.

**Comment by gattia** [comment]
Thanks for the quick reply. I did look briefly at the paper, and they do say they project the results back onto the original mesh, but clearly not fully. 

Thats a great suggestions. Im guessing using something like this: 

https://www.fwilliams.info/point-cloud-utils/sections/closest_point_on_mesh/#finding-closest-points-between-point-clouds-and-meshes

to get the points on the original mesh continuously based on the barycentric coords instead of at discrete locations.
