### ISSUE TITLE
Error in deduplicate returns

### ISSUE THREAD

**Issue by gattia** [fwilliams/point-cloud-utils#72]
I tried deduplicate and it returned things that weren't the expected shapes. I took a peak at the underlying function [here](https://github.com/fwilliams/point-cloud-utils/blob/04abee0013ffa067600ae7190ec8b77cf3b8081d/src/remove_duplicates.cpp#L85C5-L85C35) and noticed it c[alls igl to do the deduplicating](https://github.com/libigl/libigl/blob/deae7a2767252f40490f92a499e32c396b8ce681/include/igl/remove_duplicate_vertices.h#L44-L52).

Looks like IGL expects the order of inputs to be: 
- verts
- faces
- epsilon
- v_out
- SVI #SV by 1 list of indices so SV = V(SVI,:) 
- SVJ #V by 1 list of indices so V = SV(SVJ,:)
- faces_out

But it is input as: 
- verts
- faces
- epsilon
- v_out
- faces_out
- SVI #SV by 1 list of indices so SV = V(SVI,:) 
- SVJ #V by 1 list of indices so V = SV(SVJ,:)

This results in a swapping of the outputs so all of faces_out, SVI and SVJ are swapped with one another.

**Comment by fwilliams** [comment]
Thanks for finding this! If you send a PR fixing this and add a small test, I'll merge it in!

**Comment by gattia** [comment]
Will look into it and make a pull.

**Comment by fwilliams** [comment]
Thanks so much!!

**Comment by fwilliams** [comment]
Fixed by #74
