### ISSUE TITLE
error with pip install

### ISSUE THREAD

**Issue by xiazhiwang** [fwilliams/point-cloud-utils#8]
Hi, thanks for your excellent work. But I have error when I use pip install, could you please help me ? The error is shown below:

    [  2%] Building C object geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/LM7/libmeshb7.c.o
    In file included from /tmp/pip-hhokn49i-build/external/numpyeigen/external/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/external/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/external/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/external/pybind11/include/pybind11/pybind11.h:44,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/cmake/../src/npe_sparse_array.h:4,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/src/npe_typedefs.h:6,
                     from /tmp/pip-hhokn49i-build/external/numpyeigen/src/npe_typedefs.cpp:1:
    /tmp/pip-hhokn49i-build/external/numpyeigen/external/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    CMakeFiles/npe.dir/build.make:62: recipe for target 'CMakeFiles/npe.dir/external/numpyeigen/src/npe_typedefs.cpp.o' failed
    make[2]: *** [CMakeFiles/npe.dir/external/numpyeigen/src/npe_typedefs.cpp.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/npe.dir/all' failed
    make[1]: *** [CMakeFiles/npe.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

    [ 20%] Built target geogram_third_party
    Makefile:162: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-hhokn49i-build/setup.py", line 113, in <module>
        main()
      File "/tmp/pip-hhokn49i-build/setup.py", line 108, in main
        test_suite="tests"
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-hhokn49i-build/setup.py", line 39, in run
        self.build_extension(ext)
      File "/tmp/pip-hhokn49i-build/setup.py", line 68, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-hhokn49i-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp
/pip-sfteyg7z-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-hhokn49i-build/

**Comment by fwilliams** [comment]
Hi, this error seems like you either don't have the CPython headers and libraries installed on your system or they are installed in some nonstandard location. 

The easiest solution to your problem is to use (`conda`)[https://docs.conda.io/en/latest/] to install the package instead of `pip`. Unfortunately, `pip` only manages pure python dependencies. Since Point Cloud Utils is written in C++ it depends on certain libraries which need to be installed manually on your system. 

On the other hand, `conda` manages both python and C++ dependencies and installation should just work out of the box with no issues.

**Comment by xiazhiwang** [comment]
Thanks.
