### ISSUE TITLE
Sampling a signed distance field at uniform intervals

### ISSUE THREAD

**Issue by gursi26** [fwilliams/point-cloud-utils#80]
I'm trying to sample a signed distance field from a mesh at uniform intervals in space. I tried to follow the example code given in [this](https://github.com/fwilliams/point-cloud-utils#compute-shortest-signed-distances-to-a-triangle-mesh-with-fast-winding-numbers) section of the readme, replacing the randomly sampled `pts` array with my own array initialized like so;

```
# Creates a 3-dimensional grid of evenly spaced points
pts = np.mgrid[-1:1:100j, -1:1:100j, -1:1:100j]
pts = pts.reshape(3, -1).transpose()

sdf, _, _  = pcu.signed_distance_to_mesh(arr, verts, faces)
```

However, when I run this, I get the following error;
```
ValueError: Invalid type (double, Row Major) for argument 'v'. Expected it to match argument 'p' which is of type (double, Col Major).
```
I do not understand what this error means, the shape of my input tensor is the similar to the randomly initialized tensor in the readme, which works just fine when passed in to the function. How do I go about solving this?

**Comment by fwilliams** [comment]
Thanks for posting your issue!

pcu imposes some restrictions on having types and alignments (row vs column major) match for the arguments. Here you're transposing the points so they go from row major to column major. I'm guessing `arr` is row major.

To fix this issue, replace the line `pts = pts.reshape(3, -1).transpose()` with `pts = np.ascontiguousarray(pts.reshape(3, -1).transpose())`

**Comment by gursi26** [comment]
It works! Thanks for the quick response :)
