### ISSUE TITLE
How can i compare two ply files?

### ISSUE THREAD

**Issue by sathiz91** [fwilliams/point-cloud-utils#9]
How to utilize your library to read two PLY files and compare the distance (distance matrix or similarity matrix). Thanks in  advance.

**Comment by fwilliams** [comment]
By distance matrix, do you mean pairwise distances between two point clouds? 
i.e. if P1 is a n x 3 matrix where each row is a point, and P2 is a m x 3 matrix where each row is a point, then the pairwise distance matrix would have entries D_{i, j} = ||P1_i - P2_j||_2.

If that's what you mean, then you can use `pcu.pairwise_distances`. For example:

```
import point_cloud_utils as pcu

p1, f1, n1, uv1 = pcu.read_ply("first.ply")
p2, f1, n1, uv1 = pcu.read_ply("second.ply")

# p1 is an array with shape [n, 3] where each row is a vertex
# p2 is an array with shape [m, 3] where each row is a vertex

# d is an array of shape [n, m] where d[i, j] = ||p1[i, :] - p1[j, :]||
d = pcu.pairwise_distances(p1, p2)
```

For more information you can read the docs for these by typing `help(pcu.read_ply)` and `help(pcu.pairwise_distances)` into a python shell

**Comment by fwilliams** [comment]
Also, please update to version 0.11.1 if you want to use odd norms. I fixed a bug related to these.

Does this answer your question? Can I close this issue?

**Comment by sathiz91** [comment]
Thank you for the quick response. I'm not using odd norms, I followed the same instruction,  P1 is (1088, 3) and P2 is (47592,3) when i do pairwise calculation i get array with full of 'inf' values.

**Comment by fwilliams** [comment]
Are you sure your data does not have inf or invalid values in it? If you post your PLYs, I can have a look.

**Comment by sathiz91** [comment]
I attached ply files, please have a Look.
[cloud-1.zip](https://github.com/fwilliams/point-cloud-utils/files/3871693/cloud-1.zip)

**Comment by fwilliams** [comment]
So I didn't have any issues running the following code:

```python
import point_cloud_utils as pcu
v1, f1, n1, uv1 = pcu.read_ply("cloud-1.ply")
v2, f2, n2, uv2 = pcu.read_ply("cloud-1full.ply")
d = pcu.pairwise_distances(v1, v2)
```

Here's the output from my shell
```
In [2]: import point_cloud_utils as pcu                                                                               

In [3]: v1, f1, n1, uv1 = pcu.read_ply("cloud-1.ply")                                                                 

In [4]: v2, f2, n2, uv2 = pcu.read_ply("cloud-1full.ply")                                                             

In [5]: d = pcu.pairwise_distances(v1, v2)                                                                            
                                                                                                                      In [6]: d                                                                                                             
Out[6]: 
array([[0.90397629, 0.90787553, 0.91021474, ..., 0.81339507, 0.93579904,
        0.92253046],
       [0.90113239, 0.90503163, 0.90737418, ..., 0.81072539, 0.9328959 ,
        0.9196325 ],
       [0.89823448, 0.90213039, 0.90447293, ..., 0.80799146, 0.92994468,
        0.91669546],
       ...,
       [0.86377497, 0.86739542, 0.8695018 , ..., 0.7747474 , 0.89527285,
        0.88282746],
       [0.87779951, 0.88165344, 0.88397727, ..., 0.78864316, 0.90917098,
        0.89607111],
       [0.88528927, 0.88913801, 0.89144767, ..., 0.79564742, 0.91682964,
        0.90372978]])

In [7]: np.max(d), np.min(d)                                                                                          
Out[7]: (1.372943658235311, 0.5676935028583245)
```

Note that the arrays are quite big so the operation eats up a lot of memory (I had to run it on a big server).

**Comment by sathiz91** [comment]
I'm using Intel® Core™ i5-9400F , with 16GB RAM. I'm running it on conda environment with the latest version(0.11.1). I used the same file, but the results were no way near to yours. 

>>> p1,f1,n1,uv1 = pcu.read_ply('./load/cloud-1.ply')
>>> p2,f2,n2,uv2 = pcu.read_ply('./input/cloud-1full.ply')
>>> d = pcu.pairwise_distances(p1,p2)
>>> d
array([[ 0., inf, inf, ..., inf, inf, inf],
[inf,  0., inf, ..., inf, inf, inf],
[inf, inf,  0., ..., inf, inf, inf],
...,
[inf, inf, inf, ...,  0., inf, inf],
[inf, inf, inf, ..., inf,  0., inf],
[inf, inf, inf, ..., inf, inf,  0.]])
>>> np.max(d)
inf
>>> np.min(d)
0.0
>>>

**Comment by fwilliams** [comment]
Can you run the following?

```
p1,f1,n1,uv1 = pcu.read_ply('./load/cloud-1.ply')
p2,f2,n2,uv2 = pcu.read_ply('./input/cloud-1full.ply')

print(p1.shape, np.min(p1), np.max(p1), np.mean(p1))
print(p2.shape, np.min(p2), np.max(p2), np.mean(p2))
```

**Comment by fwilliams** [comment]
Also what OS are you using?

**Comment by sathiz91** [comment]
I'm using ubuntu 16.04 LTS, please find the results, 
>>> print(p1.shape, np.min(p1), np.max(p1), np.mean(p1))
(15864, 3) 3.0517584800215326e-05 0.6956068277359009 0.24418866964744965
>>> print(p2.shape, np.min(p2), np.max(p2), np.mean(p2))
(47592, 3) -0.2364010065793991 0.6943179965019226 0.23413198912436622

**Comment by fwilliams** [comment]
I can't seem to reproduce your bug on my machine with Ubuntu and 16GB of RAM. 

Are you using conda? What version of Numpy are you using?

Can you also print the dtype of the arrays?
i.e.
```python
print(p1.dtype, p2.dtype)
```

**Comment by fwilliams** [comment]
@sathiz91 any updates on this? Did you ever manage to make it work?
